version: "3.4"

services:
  # tradingapp.api:
  #   image: ${DOCKER_REGISTRY-}tradingapi
  #   build:
  #     context: .
  #     dockerfile: TradingWebApi/Dockerfile
  #   ports:
  #     - "7047:443"
  #     - "7048:80"
  #   depends_on:
  #     - "rabbitmq"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"