name: Publish TradingApi

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'src/TradingApp.TradingViewProvider/**'
    - 'src/TradingApp.TradingWebApi/**'
    - 'src/**'
    - 'tests/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore
        run: dotnet restore ./TradingApp.sln
      
      - name: Build
        run: dotnet build ./TradingApp.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./TradingApp.sln --configuration Release --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      
      - name: Codecov
        uses: codecov/codecov-action@v1

      - name: Publish
        run: dotnet publish ./TradingApp.sln --configuration Release --no-build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: tradingViewApp
          path: ./TradingApp.sln
