name: Publish TradingApi

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/TradingApp.TradingViewProvider/**'
    - 'src/TradingApp.TradingWebApi/**'
    - 'src/**'
    - 'tests/**'
    - 'ui/**'
env:
  DOTNET_VERSION: "7.0.x"

jobs:
  Build_backend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}     

      - name: Nuke Build
        shell: bash
        run: ./build.sh --target BuildBackend --verbosity verbose

  Build_frontend:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Nuke Build
        shell: bash
        run: ./build.sh --target BuildFrontend --verbosity verbose