name: Publish TradingApi

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'src/TradingApp.TradingViewProvider/**'
    - 'src/TradingApp.TradingWebApi/**'
    - 'src/**'
    - 'tests/**'
    - 'ui/**'
jobs:
  Build_backend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore
        run: dotnet restore ./TradingApp.sln
      
      - name: Build
        run: dotnet build ./TradingApp.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./TradingApp.sln --configuration Release --no-restore /p:CollectCoverage=true --collect:"XPlat Code Coverage" --logger trx

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
  Build_ui:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        working-directory: ./ui/trading-app

      - name: Run the tests
        run: npm test
        working-directory: ./ui/trading-app

      - name: Run the test coverage
        run: npm coverage
        working-directory: ./ui/trading-app

      - name: Build
        run: npm run build
        working-directory: ./ui/trading-app
  Deploy:
    needs: [Build_backend, Build_ui]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: dotnet publish ./TradingApp.sln --configuration Release --no-build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: tradingViewApp
          path: ./TradingApp.sln